version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - github-actions
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - docker
    ignore:
      - dependency-name: node
        versions: ['>= 17.x'] # currently 16.x is the LTS
