version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
    reviewers:
      - devpow112
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
    reviewers:
      - devpow112
    ignore:
      - dependency-name: node
        versions: ['>= 15.x'] # currently 14.x is the LTS
